<?php
/**
 * @file AbstractAnalyzer.php
 * An abstract basic class for analyzing parsing trees generated by Parser
 * Lang en
 * Created at: 2025-06-15
 * Reviewstatus: 2026-06-15
 * Localization: complete
 * Documentation: complete
 * Tests: Unit/Parser/AbstractAnalyzerTest.php
 * Coverage Unit: 
 */

namespace Sunhill\Parser;

use Sunhill\Basic\Base;
use Sunhill\Parser\Nodes\Node;
use Sunhill\Parser\Nodes\ArrayNode;
use Sunhill\Parser\Nodes\BinaryNode;
use Sunhill\Parser\Nodes\StringNode;
use Sunhill\Parser\Nodes\IntegerNode;
use Sunhill\Parser\Nodes\FloatNode;
use Sunhill\Parser\Nodes\BooleanNode;
use Sunhill\Parser\Nodes\FunctionNode;
use Sunhill\Parser\Nodes\UnaryNode;
use Sunhill\Parser\Nodes\IdentifierNode;
use Sunhill\Parser\LanguageDescriptor\FunctionDescriptor;
use Sunhill\Parser\Exceptions\TypeNotExpectedException;
use Sunhill\Parser\Exceptions\IdentifierNotFoundException;
use Sunhill\Parser\Exceptions\FunctionNotFoundException;
use Sunhill\Parser\Exceptions\FunctionParameterException;
use Sunhill\Parser\Exceptions\InvalidOperatorException;
use Sunhill\Parser\Exceptions\TypeMismatchException;
use Sunhill\Parser\Exceptions\TypesMismatchException;
use Sunhill\Parser\Nodes\TimeNode;
use Sunhill\Parser\Nodes\DateTimeNode;
use Sunhill\Parser\Nodes\DateNode;
use Sunhill\Parser\Nodes\ReferenceNode;

abstract class AbstractAnalyzer extends Base
{
 
    /**
     * Returns the type of the given identifier. If the identifier is not found return null.
     * 
     * @param string $name
     * @return string|NULL
     */
    abstract protected function getTypeOfIdentifier(string $name): ?string;
    
    /**
     * Returns the FunctionDescriptor for the given function. If the function is not found returns null
     * 
     * @param string $name
     * @return FunctionDescriptor|NULL
     */
    abstract protected function getProfileOfFunction(string $name): ?FunctionDescriptor;
    
    /**
     * Returns the defined combination of types allowed for this operator (and only for this). 
     * The result is an associative array with the keys "left", "right" and "resulting". The values have to be the 
     * datatype that is accepted ("integer", "string", "float", "boolean", "date", "time", "datetime") or a pseudo 
     * type ("numeric" or "pseudoboolean")
     * 
     * @param string $operator
     * @return array|NULL
     */
    abstract protected function getProfilesOfBinaryOperator(string $operator): ?array;

    /**
     * Returns the defined combination of types allowed for this operator (and only for this).
     * The result is an associative array with the keys "child" and "resulting". The values have to be the
     * datatype that is accepted ("integer", "string", "float", "boolean", "date", "time", "datetime") or a pseudo
     * type ("numeric" or "pseudoboolean")
     *
     * @param string $operator
     * @return array|NULL
     */
    abstract protected function getProfilesOfUnaryOperator(string $operator): ?array;
    
    /**
     * This method checks the resulting datatype of the node and returns the result of the check as a boolean.
     * 
     * @param string $type
     * @return bool
     */
    abstract protected function checkAcceptedType(string $type): bool;
    
    /**
     * This method is called when the Analyzer doesn't knoe the type of the node.
     * 
     * @param Node $node
     */
    protected function prepareUnknownNode(Node $node)
    {
        // Do nothing by default    
    }
    
    /**
     * Prepared the analyzation of every element of the array
     * 
     * @param ArrayNode $node
     */
    protected function prepareArrayNode(ArrayNode $node)
    {
        for ($i=0;$i<$node->elementCount();$i++) {
            $this->prepareAnalyze($node->getElement($i));
        }
    }
    
    /**
     * Prepares a binary node by preparing both branches
     * 
     * @param BinaryNode $node
     */
    protected function prepareBinaryNode(BinaryNode $node)
    {
        if (!is_null($profiles = $this->getProfilesOfBinaryOperator($node->getType()))) {
            foreach ($profiles as $profile) {
                $node->addAllowedType($profile['left'], $profile['right'], $profile['resulting']);
            }
            $this->prepareAnalyze($node->left());
            $this->prepareAnalyze($node->right());
        }
    }
    
    /**
     * Looks up the descriptor for this function. If found set it to the node and prepare every function argument.
     * 
     * @param FunctionNode $node
     */
    protected function prepareFunctionNode(FunctionNode $node)
    {
        if (!is_null($profile = $this->getProfileOfFunction($node->getName()))) {
            $node->setFunctionDescriptor($profile);
            for ($i=0;$i<$node->getArgumentCount();$i++) {
                $this->prepareAnalyze($node->getArgument($i));
            }
        }
    }
    
    /**
     * Looks this identifier up. if found sets it type to the node
     * 
     * @param IdentifierNode $node
     */
    protected function prepareIdentifierNode(IdentifierNode $node)
    {
        if (!is_null($type = $this->getTypeOfIdentifier($node->getName()))) {
            $node->setDatatype($type);
        }
    }
    
    /**
     * First looks up the parent identifier and checks if this is a record. If yes looks up,
     * if the underlying record defines a node of this name
     * 
     * @param ReferenceNode $node
     */
    protected function preapreReferenceNode(ReferenceNode $node)
    {
        if ($this->getTypeOfIdentifier($node->getName()) === 'record') {
            
        }
    }
    
    /**
     * Looks up the profile for this unary operator. If one exsists, set the possible rules to the node and 
     * prepare the child node.
     * 
     * @param UnaryNode $node
     */
    protected function prepareUnaryNode(UnaryNode $node)
    {
        if (!is_null($profiles = $this->getProfilesOfUnaryOperator($node->getType()))) {
            foreach ($profiles as $profile) {
                $node->addAllowedType($profile['child'], $profile['resulting']);
            }
            $this->prepareAnalyze($node->child());
        }
    }
    
    /**
     * Prepares the analyzation of the node tree. This means it looks up the profiles for operators, functions and identifiers.
     * 
     * @param Node $node
     */
    protected function prepareAnalyze(Node $node)
    {
        switch ($node::class) {
            case ArrayNode::class:
                $this->prepareArrayNode($node);
                break;
            case BinaryNode::class:
                $this->prepareBinaryNode($node);
                break;
            case BooleanNode::class:
            case DateNode::class:
            case DateTimeNode::class:
            case FloatNode::class:
            case IntegerNode::class:
            case StringNode::class:
            case TimeNode::class:
                break;
            case FunctionNode::class:
                $this->prepareFunctionNode($node);
                break;
            case IdentifierNode::class:
                $this->prepareIdentifierNode($node);
                break;
            case ReferenceNode::class:
                $this->prepareReferenceNode($node);
                break;
            case UnaryNode::class:
                $this->prepareUnaryNode($node);
                break;
            default:
                $this->prepareUnknownNode($node);
        }
    }
    
    /**
     * Validates this node. if valid returns its resulting data type
     * 
     * @param Node $node
     * @return string
     */
    protected function getNodeType(Node $node): string
    {
        $node->validate();
        if (is_null($type = $node->getDatatype())) {
            
        }
        return $type;
    }
    
    /**
     * Analyzes a given node tree.
     * 
     * @param Node $node
     */
    public function analyze(Node $node)
    {
        $this->prepareAnalyze($node);
        if (!$this->checkAcceptedType($type = $this->getNodeType($node))) {
            throw new TypeNotExpectedException("The type '$type' for the given expression is not expected.");
        }
    }
    
}
