<?php

/**
 * @file AbstractAnalyzer.php
 * An abstract basic class for analyzing parsing trees generated by Parser
 * Lang en
 * Created at: 2025-06-15
 * Reviewstatus: 2026-06-15
 * Localization: complete
 * Documentation: complete
 * Tests: Unit/Parser/AbstractAnalyzerTest.php
 * Coverage Unit:
 */

namespace Sunhill\Parser;

use Sunhill\Basic\Base;
use Sunhill\Parser\Exceptions\TypeNotExpectedException;
use Sunhill\Parser\LanguageDescriptor\FunctionDescriptor;
use Sunhill\Parser\Nodes\ArrayNode;
use Sunhill\Parser\Nodes\BinaryNode;
use Sunhill\Parser\Nodes\BooleanNode;
use Sunhill\Parser\Nodes\DateNode;
use Sunhill\Parser\Nodes\DateTimeNode;
use Sunhill\Parser\Nodes\FloatNode;
use Sunhill\Parser\Nodes\FunctionNode;
use Sunhill\Parser\Nodes\IdentifierNode;
use Sunhill\Parser\Nodes\IntegerNode;
use Sunhill\Parser\Nodes\Node;
use Sunhill\Parser\Nodes\ReferenceNode;
use Sunhill\Parser\Nodes\StringNode;
use Sunhill\Parser\Nodes\TimeNode;
use Sunhill\Parser\Nodes\UnaryNode;

abstract class AbstractAnalyzer extends Base
{
    /**
     * Returns the type of the given identifier. If the identifier is not found return null.
     */
    abstract protected function getTypeOfIdentifier(string $name): ?string;

    /**
     * Returns the FunctionDescriptor for the given function. If the function is not found returns null
     */
    abstract protected function getProfileOfFunction(string $name): ?FunctionDescriptor;

    /**
     * Returns the defined combination of types allowed for this operator (and only for this).
     * The result is an associative array with the keys "left", "right" and "resulting". The values have to be the
     * datatype that is accepted ("integer", "string", "float", "boolean", "date", "time", "datetime") or a pseudo
     * type ("numeric" or "pseudoboolean")
     */
    abstract protected function getProfilesOfBinaryOperator(string $operator): ?array;

    /**
     * Returns the defined combination of types allowed for this operator (and only for this).
     * The result is an associative array with the keys "child" and "resulting". The values have to be the
     * datatype that is accepted ("integer", "string", "float", "boolean", "date", "time", "datetime") or a pseudo
     * type ("numeric" or "pseudoboolean")
     */
    abstract protected function getProfilesOfUnaryOperator(string $operator): ?array;

    /**
     * This method checks the resulting datatype of the node and returns the result of the check as a boolean.
     */
    abstract protected function checkAcceptedType(string $type): bool;

    /**
     * This method is called when the Analyzer doesn't knoe the type of the node.
     */
    protected function prepareUnknownNode(Node $node)
    {
        // Do nothing by default
    }

    /**
     * Prepared the analyzation of every element of the array
     */
    protected function prepareArrayNode(ArrayNode $node)
    {
        for ($i = 0; $i < $node->elementCount(); $i++) {
            $this->prepareAnalyze($node->getElement($i));
        }
    }

    /**
     * Prepares a binary node by preparing both branches
     */
    protected function prepareBinaryNode(BinaryNode $node)
    {
        if (! is_null($profiles = $this->getProfilesOfBinaryOperator($node->getType()))) {
            foreach ($profiles as $profile) {
                $node->addAllowedType($profile['left'], $profile['right'], $profile['resulting']);
            }
            $this->prepareAnalyze($node->left());
            $this->prepareAnalyze($node->right());
        }
    }

    /**
     * Looks up the descriptor for this function. If found set it to the node and prepare every function argument.
     */
    protected function prepareFunctionNode(FunctionNode $node)
    {
        if (! is_null($profile = $this->getProfileOfFunction($node->getName()))) {
            $node->setFunctionDescriptor($profile);
            for ($i = 0; $i < $node->getArgumentCount(); $i++) {
                $this->prepareAnalyze($node->getArgument($i));
            }
        }
    }

    /**
     * Looks this identifier up. if found sets it type to the node
     */
    protected function prepareIdentifierNode(IdentifierNode $node)
    {
        if (! is_null($type = $this->getTypeOfIdentifier($node->getName()))) {
            $node->setDatatype($type);
        }
    }

    /**
     * First looks up the parent identifier and checks if this is a record. If yes looks up,
     * if the underlying record defines a node of this name
     */
    protected function preapreReferenceNode(ReferenceNode $node)
    {
        if ($this->getTypeOfIdentifier($node->getName()) === 'record') {

        }
    }

    /**
     * Looks up the profile for this unary operator. If one exsists, set the possible rules to the node and
     * prepare the child node.
     */
    protected function prepareUnaryNode(UnaryNode $node)
    {
        if (! is_null($profiles = $this->getProfilesOfUnaryOperator($node->getType()))) {
            foreach ($profiles as $profile) {
                $node->addAllowedType($profile['child'], $profile['resulting']);
            }
            $this->prepareAnalyze($node->child());
        }
    }

    /**
     * Prepares the analyzation of the node tree. This means it looks up the profiles for operators, functions and identifiers.
     */
    protected function prepareAnalyze(Node $node)
    {
        if (is_a($node, ArrayNode::class)) {
            $this->prepareArrayNode($node);

            return;
        }
        if (is_a($node, BinaryNode::class)) {
            $this->prepareBinaryNode($node);

            return;
        }
        if (is_a($node, BooleanNode::class) ||
            is_a($node, DateNode::class) ||
            is_a($node, DateTimeNode::class) ||
            is_a($node, FloatNode::class) ||
            is_a($node, IntegerNode::class) ||
            is_a($node, StringNode::class) ||
            is_a($node, TimeNode::class)) {
            return;
        }
        if (is_a($node, FunctionNode::class)) {
            $this->prepareFunctionNode($node);

            return;
        }
        if (is_a($node, IdentifierNode::class)) {
            $this->prepareIdentifierNode($node);

            return;
        }
        if (is_a($node, ReferenceNode::class)) {
            $this->prepareReferenceNode($node);

            return;
        }
        if (is_a($node, UnaryNode::class)) {
            $this->prepareUnaryNode($node);

            return;
        }
        $this->prepareUnknownNode($node);
    }

    /**
     * Validates this node. if valid returns its resulting data type
     */
    protected function getNodeType(Node $node): string
    {
        $node->validate();
        if (is_null($type = $node->getDatatype())) {

        }

        return $type;
    }

    /**
     * Analyzes a given node tree.
     */
    public function analyze(Node $node)
    {
        $this->prepareAnalyze($node);
        if (! $this->checkAcceptedType($type = $this->getNodeType($node))) {
            throw new TypeNotExpectedException("The type '$type' for the given expression is not expected.");
        }
    }
}
