<?php
/**
 * @file Analyzer.php
 * A basic class for analyzing parsing trees generated by Parser
 * Lang en
 * Reviewstatus: 2025-02-28
 * Localization: complete
 * Documentation: complete
 * Tests: Unit/Parser/AnalyzerTest.php
 * Coverage Unit: 80.17% (2025-06-06)
 */

namespace Sunhill\Parser;

use Sunhill\Basic\Base;
use Sunhill\Parser\LanguageDescriptor\LanguageDescriptor;
use Sunhill\Parser\Nodes\Node;
use Sunhill\Parser\Nodes\ArrayNode;
use Sunhill\Parser\Nodes\BinaryNode;
use Sunhill\Parser\Nodes\StringNode;
use Sunhill\Parser\Nodes\IntegerNode;
use Sunhill\Parser\Nodes\FloatNode;
use Sunhill\Parser\Nodes\BooleanNode;
use Sunhill\Parser\Nodes\FunctionNode;
use Sunhill\Parser\Nodes\UnaryNode;
use Sunhill\Parser\Nodes\IdentifierNode;
use Sunhill\Parser\LanguageDescriptor\OperatorDescriptor;
use Sunhill\Parser\LanguageDescriptor\FunctionDescriptor;
use Sunhill\Parser\Exceptions\TypeNotExpectedException;
use Sunhill\Parser\Exceptions\IdentifierNotFoundException;
use Sunhill\Parser\Exceptions\FunctionNotFoundException;
use Sunhill\Parser\Exceptions\FunctionParameterException;
use Sunhill\Parser\Exceptions\InvalidOperatorException;
use Sunhill\Parser\Exceptions\TypeMismatchException;

class Analyzer extends Base
{
    
    protected array $accepted_operators = [];
    
    protected array $predefined_functions = [];
    
    protected array $predefined_identifiers = [];
    
    protected array $accepted_types = [];
    
    public function addOperatorTypes(string $operator, array $types)
    {
        if (isset($this->accepted_operators[$operator])) {
            $this->accepted_operators[$operator][] = $types;
        } else {
            $this->accepted_operators[$operator] = [$types];
        }
        
        return $this;
    }
    
    public function addIdentifier(string $name, string $type)
    {
        $this->predefined_identifiers[$name] = $type;
        
        return $this;
    }
    
    public function addFunction(string $name, string $return_type): FunctionDescriptor
    {
        $func = new FunctionDescriptor($name);
        $func->setReturnType($return_type);
        $this->predefined_functions[$name] = $func;
        
        return $func;
    }
    
    public function addAcceptedType(string $type)
    {
        $this->accepted_types[] = $type;
        
        return $this;
    }
    
    public function loadLanguageDescriptor(LanguageDescriptor $descriptor)
    {
    }

    /**
     * Tests if the test rule $test matches the given rule $rule and takes care of pseudo 
     * types like numeric and pseudoboolean
     * 
     * @param string $test
     * @param string $rule
     * @return boolean
     */
    private function typeMatch(string $test, string $rule)
    {
        switch ($rule) {
            case 'pseudoboolean':
                return in_array($test,['boolean','integer','float','string']);
            case 'numeric':
            case 'float':
                return in_array($test,['integer','float']);
            default:
                return $test == $rule;
        }
    }
    
    /**
     * Checks if the given rules match the given types
     * 
     * @param array $test
     * @param array $rule
     * @return bool
     */
    private function typesMatch(array $test, array $rule): bool
    {
        if (count($test) !== count($rule)-1) {
            return false;
        }
        for ($i=0;$i<count($test);$i++) {
            if (!$this->typeMatch($test[$i], $rule[$i])) {
                return false;
            }
        }
        return true;
    }
    
    protected function analyzeBinaryNode(BinaryNode $node)
    {
        $this->analyzeNode($node->left());
        $left_type = $this->getTypeOfNode($node->left());
        $this->analyzeNode($node->right());
        $right_type = $this->getTypeOfNode($node->right());
        
    }
    
    private function getBinarySignature($left, $right, $operator)
    {
        foreach ($this->accepted_operators[$operator] as $types) {
            if ($this->typesMatch([$left,$right],$types)) {
                return $types[2];
            }
        }
        return 'invalid';
    }
    
    /**
     * Returns the type of the binary node
     * 
     * @param BinaryNode $node
     * @return unknown
     */
    protected function getTypeOfBinaryNode(BinaryNode $node)
    {
        if (!isset($this->accepted_operators[$node->getType()])) {
            throw new InvalidOperatorException("The operator ".$node->getType()." is not expected");
        }
        $left = $this->getTypeOfNode($node->left());
        $right = $this->getTypeOfNode($node->right());
        $type = $this->getBinarySignature($left, $right, $node->getType());
        
        if ($type == 'invalid') {
            throw new TypeMismatchException("The operator ".$node->getType()." does not handle '$left' and '$right'");
        }
        return $type;
    }
    
// =================================== Function handling ============================================    
    private function buildExpectedParameters(FunctionDescriptor $descriptor): array
    {
        $result = $descriptor->getParameterDescriptors();
        if ($descriptor->getUnlimitedParameters()) {
            for ($i=0;$i<$descriptor->getMinimumParameterCount();$i++) {
                $entry = new \stdClass();
                $entry->type = $descriptor->getUnlimitedType();
                $entry->optional = false;
                $result[] = $entry;
            }
            $entry = new \stdClass();
            $entry->type = $descriptor->getUnlimitedType();
            $entry->optional = true;
            $entry->dontshift = true;
            $result[] = $entry;
        }
        return $result;
    }
    
    private function buildGivenParameters(FunctionNode $node): array
    {
        $result = [];
        for ($i=0;$i<$node->getArgumentCount();$i++) {
            $result[] = $this->getTypeOfNode($node->getArgument($i));
        }
        return $result;        
    }
    
    private function getExpectedParameter(&$expected)
    {
       $parameter = array_shift($expected);
       if (isset($parameter->dontshift)) {
           array_unshift($expected, $parameter);
       }
       return $parameter;
    }
    
    private function checkParameters(FunctionNode $node, FunctionDescriptor $descriptor)
    {
        $expected = $this->buildExpectedParameters($descriptor);
        $given = $this->buildGivenParameters($node);
        while (!empty($given)) {
            $given_parameter = array_shift($given);
            $expected_parameter = $this->getExpectedParameter($expected);
            if (is_null($expected_parameter)) {
                throw new FunctionParameterException("Too many parameters.");
            }
            if (!$this->typeMatch($given_parameter,$expected_parameter->type)) {
                throw new FunctionParameterException("Parameter type mismatch. Expected '".$expected_parameter->type."', got '$given_parameter'");
            }            
        }
        if (!empty($expected)) {
            $expected_parameter = $this->getExpectedParameter($expected);
            if (!$expected_parameter->optional) {
                throw new FunctionParameterException("Too few parameters. Expected ".$expected_parameter->type);
            }
        }
    }
    
    protected function analyzeFunctionNode(FunctionNode $node, $descriptor)
    {
        $this->checkParameters($node, $descriptor);
    }
    
    private function tryToLookupFunctionDescriptor(FunctionNode $node): FunctionDescriptor|string
    {
        return 'unknown';    
    }
    
    private function getFunctionDescriptor(FunctionNode $node): FunctionDescriptor|string
    {
        if (isset($this->predefined_functions[$node->name()])) {
            return $this->predefined_functions[$node->name()];
        } 
        return $this->tryToLookupFunctionDescriptor($node);
    }
  
    /**
     * Returns the return type of the given function
     * 
     * @param FunctionNode $node
     * @return unknown
     */
    protected function getTypeOfFunctionNode(FunctionNode $node)
    {
        if (($func = $this->getFunctionDescriptor($node)) === 'unknown') {
            throw new FunctionNotFoundException("The function '".$node->name()."' was not found.");
        }
        $this->analyzeFunctionNode($node, $func);
        return $func->getReturnType();        
    }

 // ================================ Unary node ==============================================
    
    /**
     * Returns the type of the given unary node
     * 
     * @param UnaryNode $node
     * @return unknown|string
     */
    protected function getTypeOfUnaryNode(UnaryNode $node)
    {
        $child = $this->getTypeOfNode($node->child());
        if (!isset($this->accepted_operators[$node->getType()])) {
            // Exception
        }
        foreach ($this->accepted_operators[$node->getType()] as $types) {
            if ($this->typesMatch([$child],$types)) {
                return $types[1];
            }
        }
        return 'invalid';
    }
    
// ================================== Identifier ================================================    
    protected function tryToLookupIdentifierType(string $identifier): string
    {
        return 'unknown';    
    }
    
    protected function getIdentifierType(IdentifierNode $node): string
    {
        if (!isset($this->predefined_identifiers[$node->getName()])) {
            $result = $this->tryToLookupIdentifierType($node->getName());
            if ($result == 'unknown') {
                throw new IdentifierNotFoundException("The identifier '".$node->getName()."' was not found.");                
            }
        }
        return $this->predefined_identifiers[$node->getName()];
    }
    
    /**
     * Returns the type of the identifer
     * 
     * @param IdentifierNode $node
     */
    protected function getTypeOfIdentifierNode(IdentifierNode $node)
    {
        if (isset($this->predefined_identifiers[$node->getName()])) {
            return $this->predefined_identifiers[$node->getName()];
        }
        throw new IdentifierNotFoundException("The identifier '".$node->getName()."' was not found.");
    }
    
    protected function getTypeOfNode(Node $node)
    {
        switch ($node::class) {
            case ArrayNode::class:
                return 'array';
                break;
            case BinaryNode::class:
                return $this->getTypeOfBinaryNode($node);
                break;
            case FunctionNode::class:
                return $this->getTypeOfFunctionNode($node);
                break;
            case UnaryNode::class:
                return $this->getTypeOfUnaryNode($node);
                break;
            case BooleanNode::class:
                return 'boolean';
                break;
            case FloatNode::class:
                return 'float';
                break;
            case IntegerNode::class:
                return 'integer';
                break;
            case IdentifierNode::class:
                return $this->getTypeOfIdentifierNode($node);
            case StringNode::class:
                return 'string';
                break;
        }        
    }
    
    protected function analyzeArrayNode(ArrayNode $node)
    {
        
    }
    
    protected function checkIsTypeAccepted(string $type)
    {
        if (!in_array($type, $this->accepted_types)) {
            throw new TypeNotExpectedException("The type of the expression ($type) was not expected");
        }
    }
    
    public function analyze(Node $root_node)
    {
        $type = $this->getTypeOfNode($root_node); 
        $this->checkIsTypeAccepted($type);
        
        return $type;
    }

}
