<?php
/**
 * @file Analyzer.php
 * A basic class for analyzing parsing trees generated by Parser
 * Lang en
 * Reviewstatus: 2025-02-28
 * Localization: complete
 * Documentation: complete
 * Tests: Unit/Parser/AnalyzerTest.php
 * Coverage: 
 */

namespace Sunhill\Parser;

use Sunhill\Basic\Base;

class Analyzer extends Base
{
    
}
